name: Project
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  unit-test:
    strategy:
      matrix:
        host-os: [ubuntu-latest]
        golang-version: [1.18.x]
    runs-on: ${{ matrix.host-os }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.golang-version }}
      - name: Dependencies
        run: go mod download
      - name: Test
        run: make test
  build-marble:
    strategy:
      matrix:
        goos: [linux, darwin]
        goarch: [amd64, arm64]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18.x
      - name: Dependencies
        run: go mod download
      - name: Test
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: go build -o build/marble-${{ matrix.goos }}-${{ matrix.goarch }} ./cmd/marble
