name: Release
on:
  push:
    tags: ["v*"]
jobs:
  build-marble:
    strategy:
      matrix:
        goos: [linux, darwin]
        goarch: [amd64, arm64]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18.x
      - name: Dependencies
        run: go mod download
      - name: Build
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: go build -o build/marble-${{ github.ref }}-${{ matrix.goos }}-${{ matrix.goarch }} ./cmd/marble
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/marble-${{ github.ref }}-${{ matrix.goos }}-${{ matrix.goarch }}
          tag: ${{ github.ref }}
          overwrite: true
